### ISSUE TITLE
Errors after following the installation guide (Android)

### ISSUE THREAD

**Issue by Bohmaster** [jonathan-casarrubias/native-chat-example#3]
The build process works fine and the emulator runs the app (showing errors in the body)

```
The system failed to delete the package for an unspecified reason.
Successfully deployed on device with identifier 'emulator-5554'.
JS: EXCEPTION: Error in ./AppComponent class AppComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: No provider for Router!
JS: ORIGINAL STACKTRACE:
JS: Error: DI Exception
JS:     at NoProviderError.BaseException [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/facade/exceptions.js:27:23)
JS:     at NoProviderError.AbstractProviderError [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:43:16)
JS:     at new NoProviderError (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:80:16)
JS:     at ReflectiveInjector_._throwOrNull (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:786:19)
JS:     at ReflectiveInjector_._getByKeyDefault (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:814:25)
JS:     at ReflectiveInjector_._getByKey (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:777:25)
JS:     at ReflectiveInjector_.get (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:586:21)
JS:     at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent.template.js:47:70)
JS:     at DebugAppView.AppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:96:21)
JS:     at DebugAppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:308:44)
JS: ERROR CONTEXT:
JS: [object Object]
JS: EXCEPTION: Error in ./AppComponent class AppComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: No provider for Router!
JS: ORIGINAL STACKTRACE:
JS: Error: DI Exception
JS:     at NoProviderError.BaseException [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/facade/exceptions.js:27:23)
JS:     at NoProviderError.AbstractProviderError [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:43:16)
JS:     at new NoProviderError (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:80:16)
JS:     at ReflectiveInjector_._throwOrNull (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:786:19)
JS:     at ReflectiveInjector_._getByKeyDefault (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:814:25)
JS:     at ReflectiveInjector_._getByKey (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:777:25)
JS:     at ReflectiveInjector_.get (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:586:21)
JS:     at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent.template.js:47:70)
JS:     at DebugAppView.AppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:96:21)
JS:     at DebugAppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:308:44)
JS: ERROR CONTEXT:
JS: [object Object]
JS: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
JS: ns-renderer: EXCEPTION: Error in ./AppComponent class AppComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: No provider for Router!
JS: ORIGINAL STACKTRACE:
JS: Error: DI Exception
JS:     at NoProviderError.BaseException [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/facade/exceptions.js:27:23)
JS:     at NoProviderError.AbstractProviderError [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:43:16)
JS:     at new NoProviderError (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:80:16)
JS:     at ReflectiveInjector_._throwOrNull (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:786:19)
JS:     at ReflectiveInjector_._getByKeyDefault (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:814:25)
JS:     at ReflectiveInjector_._getByKey (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:777:25)
JS:     at ReflectiveInjector_.get (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:586:21)
JS:     at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent.template.js:47:70)
JS:     at DebugAppView.AppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:96:21)
JS:     at DebugAppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:308:44)
JS: ERROR CONTEXT:
JS: [object Object]
JS: 
JS: undefined
JS: EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./AppComponent class AppComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: No provider for Router!
JS: ORIGINAL STACKTRACE:
JS: Error: DI Exception
JS:     at NoProviderError.BaseException [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/facade/exceptions.js:27:23)
JS:     at NoProviderError.AbstractProviderError [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:43:16)
JS:     at new NoProviderError (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:80:16)
JS:     at ReflectiveInjector_._throwOrNull (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:786:19)
JS:     at ReflectiveInjector_._getByKeyDefault (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:814:25)
JS:     at ReflectiveInjector_._getByKey (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:777:25)
JS:     at ReflectiveInjector_.get (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:586:21)
JS:     at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent.template.js:47:70)
JS:     at DebugAppView.AppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:96:21)
JS:     at DebugAppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:308:44)
JS: ERROR CONTEXT:
JS: [object Object]
JS: STACKTRACE:
JS: Error: Uncaught (in promise): EXCEPTION: Error in ./AppComponent class AppComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: No provider for Router!
JS: ORIGINAL STACKTRACE:
JS: Error: DI Exception
JS:     at NoProviderError.BaseException [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/facade/exceptions.js:27:23)
JS:     at NoProviderError.AbstractProviderError [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:43:16)
JS:     at new NoProviderError (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:80:16)
JS:     at ReflectiveInjector_._throwOrNull (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:786:19)
JS:     at ReflectiveInjector_._getByKeyDefault (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:814:25)
JS:     at ReflectiveInjector_._getByKey (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:777:25)
JS:     at ReflectiveInjector_.get (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:586:21)
JS:     at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent.template.js:47:70)
JS:     at DebugAppView.AppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:96:21)
JS:     at DebugAppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:308:44)
JS: ERROR CONTEXT:
JS: [object Object]
JS:     at resolvePromise (/data/data/az.nativescript.admin/files/app/tns_modules/zone.js/dist/zone-node.js:496:32)
JS:     at /data/data/az.nativescript.admin/files/app/tns_modules/zone.js/dist/zone-node.js:532:18
JS:     at ZoneDelegate.invokeTask (/data/data/az.nativescript.admin/files/app/tns_modules/zone.js/dist/zone-node.js:314:38)
JS:     at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:44:41)
JS:     at ZoneDelegate.invokeTask (/data/data/az.nativescript.admin/files/app/tns_modules/zone.js/dist/zone-node.js:313:43)
JS:     at Zone.runTask (/data/data/az.nativescript.admin/files/app/tns_modules/zone.js/dist/zone-node.js:214:48)
JS:     at drainMicroTaskQueue (/data/data/az.nativescript.admin/files/app/tns_modules/zone.js/dist/zone-node.js:432:36)
JS: Unhandled Promise rejection: EXCEPTION: Error in ./AppComponent class AppComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: No provider for Router!
JS: ORIGINAL STACKTRACE:
JS: Error: DI Exception
JS:     at NoProviderError.BaseException [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/facade/exceptions.js:27:23)
JS:     at NoProviderError.AbstractProviderError [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:43:16)
JS:     at new NoProviderError (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:80:16)
JS:     at ReflectiveInjector_._throwOrNull (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:786:19)
JS:     at ReflectiveInjector_._getByKeyDefault (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:814:25)
JS:     at ReflectiveInjector_._getByKey (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:777:25)
JS:     at ReflectiveInjector_.get (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:586:21)
JS:     at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent.template.js:47:70)
JS:     at DebugAppView.AppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:96:21)
JS:     at DebugAppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:308:44)
JS: ERROR CONTEXT:
JS: [object Object] ; Zone: angular ; Task: Promise.then ; Value: EXCEPTION: Error in ./AppComponent class AppComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: No provider for Router!
JS: ORIGINAL STACKTRACE:
JS: Error: DI Exception
JS:     at NoProviderError.BaseException [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/facade/exceptions.js:27:23)
JS:     at NoProviderError.AbstractProviderError [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:43:16)
JS:     at new NoProviderError (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:80:16)
JS:     at ReflectiveInjector_._throwOrNull (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:786:19)
JS:     at ReflectiveInjector_._getByKeyDefault (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:814:25)
JS:     at ReflectiveInjector_._getByKey (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:777:25)
JS:     at ReflectiveInjector_.get (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:586:21)
JS:     at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent.template.js:47:70)
JS:     at DebugAppView.AppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:96:21)
JS:     at DebugAppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:308:44)
JS: ERROR CONTEXT:
JS: [object Object]
JS: Error: Uncaught (in promise): EXCEPTION: Error in ./AppComponent class AppComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: No provider for Router!
JS: ORIGINAL STACKTRACE:
JS: Error: DI Exception
JS:     at NoProviderError.BaseException [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/facade/exceptions.js:27:23)
JS:     at NoProviderError.AbstractProviderError [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:43:16)
JS:     at new NoProviderError (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:80:16)
JS:     at ReflectiveInjector_._throwOrNull (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:786:19)
JS:     at ReflectiveInjector_._getByKeyDefault (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:814:25)
JS:     at ReflectiveInjector_._getByKey (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:777:25)
JS:     at ReflectiveInjector_.get (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:586:21)
JS:     at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent.template.js:47:70)
JS:     at DebugAppView.AppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:96:21)
JS:     at DebugAppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:308:44)
JS: ERROR CONTEXT:
JS: [object Object]
JS: Unhandled Promise rejection: EXCEPTION: Error in ./AppComponent class AppComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: No provider for Router!
JS: ORIGINAL STACKTRACE:
JS: Error: DI Exception
JS:     at NoProviderError.BaseException [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/facade/exceptions.js:27:23)
JS:     at NoProviderError.AbstractProviderError [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:43:16)
JS:     at new NoProviderError (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:80:16)
JS:     at ReflectiveInjector_._throwOrNull (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:786:19)
JS:     at ReflectiveInjector_._getByKeyDefault (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:814:25)
JS:     at ReflectiveInjector_._getByKey (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:777:25)
JS:     at ReflectiveInjector_.get (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:586:21)
JS:     at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent.template.js:47:70)
JS:     at DebugAppView.AppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:96:21)
JS:     at DebugAppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:308:44)
JS: ERROR CONTEXT:
JS: [object Object] ; Zone: <root> ; Task: Promise.then ; Value: EXCEPTION: Error in ./AppComponent class AppComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: No provider for Router!
JS: ORIGINAL STACKTRACE:
JS: Error: DI Exception
JS:     at NoProviderError.BaseException [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/facade/exceptions.js:27:23)
JS:     at NoProviderError.AbstractProviderError [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:43:16)
JS:     at new NoProviderError (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:80:16)
JS:     at ReflectiveInjector_._throwOrNull (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:786:19)
JS:     at ReflectiveInjector_._getByKeyDefault (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:814:25)
JS:     at ReflectiveInjector_._getByKey (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:777:25)
JS:     at ReflectiveInjector_.get (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:586:21)
JS:     at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent.template.js:47:70)
JS:     at DebugAppView.AppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:96:21)
JS:     at DebugAppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:308:44)
JS: ERROR CONTEXT:
JS: [object Object]
JS: Error: Uncaught (in promise): EXCEPTION: Error in ./AppComponent class AppComponent_Host - inline template:0:0
JS: ORIGINAL EXCEPTION: No provider for Router!
JS: ORIGINAL STACKTRACE:
JS: Error: DI Exception
JS:     at NoProviderError.BaseException [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/facade/exceptions.js:27:23)
JS:     at NoProviderError.AbstractProviderError [as constructor] (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:43:16)
JS:     at new NoProviderError (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:80:16)
JS:     at ReflectiveInjector_._throwOrNull (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:786:19)
JS:     at ReflectiveInjector_._getByKeyDefault (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:814:25)
JS:     at ReflectiveInjector_._getByKey (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:777:25)
JS:     at ReflectiveInjector_.get (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:586:21)
JS:     at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent.template.js:47:70)
JS:     at DebugAppView.AppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:96:21)
JS:     at DebugAppView.create (/data/data/az.nativescript.admin/files/app/tns_modules/@angular/core/src/linker/view.js:308:44)
JS: ERROR CONTEXT:
JS: [object Object]
```

ENVIRONMENT

> Ubuntu 14.04 64bits
> Node 5.7.0
> NPM 3.10.5

**Comment by jonathan-casarrubias** [comment]
Hey @Bohmaster, could you start from scratch? I just pushed the part 4 of the tutorial, so just clone the project again -not over the buggy one- and it should work.

Last week I needed to refactor the app because it is not using the router-deprecated anymore.

I have created an empty folder and followed the README instructions and everything now runs well, please be aware that -unfortunately- the final code is different from the articles 1,2 and 3. I will try to update these after I publish part 4 that includes the code I just pushed for you to be able to build and run.

Again, I just followed the readme instructions and now it does work.

Cheers,
Jon!!

**Comment by Bohmaster** [comment]
@jonathan-casarrubias Great! I'l try it right now and I'll let you know how it goes!

**Comment by Bohmaster** [comment]
I've tried it and now I get this error:

![screenshot from 2016-07-06 21 05 37](https://cloud.githubusercontent.com/assets/9263561/16638433/a3c423e0-43bd-11e6-86f9-d3b79dc91d75.png)

@jonathan-casarrubias 

If you want I'll wait until everything is commited and tested. Let me know how can I help you.

**Comment by jonathan-casarrubias** [comment]
@Bohmaster that is a really strange error stack.

When you get an application related issue, you get the trace to the generated JS File line, like the first issue you had; that was an application level issue, but this stack does not contain reference to a JS file, so I don't think is an application issue.

I usually use devices and it does work, but I see you are using the emulator, so I tried in genymotion and it does work also, so I don't think is a device/emualtor thing:

<img width="1127" alt="screen shot 2016-07-06 at 7 29 05 pm" src="https://cloud.githubusercontent.com/assets/1533239/16638817/f21422ce-43af-11e6-941d-b48a5cf33d40.png">

I have the following versions:

NativeScript: 2.1.0
Node: 4.4.7 (Recommended by nativescript, but I also tried using V6)

Make sure you have the latest version of nativescript because I did upgrade everything, it may be a core issue, and things changed in nativescript-angular 0.2.0.

**Comment by Bohmaster** [comment]
@jonathan-casarrubias How can I know what version of nativescript do I have? If I do "tns --version" I get  "1.6.0". I'll try to ensure having the proper NativeSript version.

EDIT:

From nativescript FAQ: 

> **How do I check which version of NativeScript does my project use?**
> Open your app’s package.json file and check the version of the "tns-core-modules" dependency.

I think I have the right version. I'll try to re-install and change some environment settings and let you know. 

Thank you for your rapid response!

**Comment by Bohmaster** [comment]
Now everything is working fine.

I've reinstalled everything (even OS)

Ubuntu 16.04
Node latest 6.X.X

**Comment by jonathan-casarrubias** [comment]
OMG @Bohmaster you really needed to start from scratch, is good to see it worked.

Cheers
Jon
